//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiziYorumProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMAKALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMAKALE()
        {
            this.TBLYORUM = new HashSet<TBLYORUM>();
        }
    
        public int MAKALEID { get; set; }
        public string MAKALEBASLIK { get; set; }
        public string MAKALEICERIK { get; set; }
        public Nullable<System.DateTime> MAKALETARIH { get; set; }
        public string MAKALEYAZAR { get; set; }
        public Nullable<byte> MAKALETUR { get; set; }
        public Nullable<byte> MAKALEKATEGORI { get; set; }
    
        public virtual TBLKATEGORI TBLKATEGORI { get; set; }
        public virtual TBLTUR TBLTUR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLYORUM> TBLYORUM { get; set; }
    }
}
